// ─────────────────────────────────────────────────────────────────────────────
// src/types/index.ts — Core type definitions for the Coogent extension
// ─────────────────────────────────────────────────────────────────────────────

import type { SessionSummary } from '../session/SessionManager.js';

// ═══════════════════════════════════════════════════════════════════════════════
//  0. Conversation Mode — Controls how subtask conversations are managed
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Controls how the AI chat conversation is managed across subtask phases.
 * - `isolated`: Each subtask opens a new conversation (zero-context, default).
 * - `continuous`: All subtasks share the same conversation (context carries over).
 * - `smart`: Automatically starts a new conversation when estimated token usage
 *   crosses a configurable threshold.
 */
export type ConversationMode = 'isolated' | 'continuous' | 'smart';

/** Configuration for conversation management across subtasks. */
export interface ConversationSettings {
    /** Active conversation mode. */
    mode: ConversationMode;
    /** Token threshold for smart-switch mode (default: 80_000). */
    smartSwitchTokenThreshold: number;
}

/** Default conversation settings. */
export const DEFAULT_CONVERSATION_SETTINGS: ConversationSettings = {
    mode: 'isolated',
    smartSwitchTokenThreshold: 80_000,
};

/** Canonical filename for the persisted runbook. */
export const RUNBOOK_FILENAME = '.task-runbook.json';

// ═══════════════════════════════════════════════════════════════════════════════
//  Branded Types — nominal type safety for opaque IDs and timestamps
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Nominal branded type for phase identifiers.
 * Prevents accidental mix-ups between phase IDs and other numbers.
 */
export type PhaseId = number & { readonly __brand: 'PhaseId' };

/**
 * Unix timestamp in milliseconds (Date.now()-style).
 * Branded to distinguish from plain numbers.
 */
export type UnixTimestampMs = number & { readonly __brand: 'UnixTimestampMs' };

/** Cast a plain number to a branded PhaseId. */
export function asPhaseId(n: number): PhaseId {
    return n as PhaseId;
}

/** Cast Date.now() or similar to a branded UnixTimestampMs. */
export function asTimestamp(ms: number = Date.now()): UnixTimestampMs {
    return ms as UnixTimestampMs;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  1. Runbook Data Model — .task-runbook.json schema
//
//  Naming convention (#92):
//    - snake_case for JSON-persisted fields (project_id, context_files, depends_on)
//    - camelCase for TypeScript-only runtime fields (smartSwitchTokenThreshold)
// ═══════════════════════════════════════════════════════════════════════════════

/** Status of an individual phase within the runbook. */
export type PhaseStatus = 'pending' | 'running' | 'completed' | 'failed';

/** A single micro-task within the runbook execution plan. */
export interface Phase {
    /** Sequential identifier (or DAG node ID in V2). */
    readonly id: PhaseId;
    /** Current execution status. */
    status: PhaseStatus;
    /** The explicit instruction to inject into the ephemeral worker agent. */
    prompt: string;
    /** Exact file paths (relative to workspace root) to read and inject.
     *  W-11: Not readonly — Engine mutates in-place. Immutability is by convention. */
    context_files: string[];
    /**
     * The condition required to mark this phase as successful.
     * V1: `"exit_code:0"` — checks process exit code.
     * V2: Regex match, compiler output, test suite result.
     */
    success_criteria: string;

    // ── Pillar 2+3 Extensions (optional, backward-compatible) ────────────

    /**
     * Phase IDs that must complete before this phase can begin.
     * Enables DAG-based parallel execution.
     * When absent, sequential ordering via `current_phase` is used.
     */
    depends_on?: readonly PhaseId[];
    /**
     * Brief context summary explaining what this phase does and why.
     * Generated by the Planner Agent to help users understand the phase at a glance.
     */
    context_summary?: string;
    /**
     * Which evaluator to use for `success_criteria`.
     * V1 default: `"exit_code"`.
     * V2+: `"regex"`, `"toolchain"`, `"test_suite"`.
     */
    evaluator?: EvaluatorType;
    /**
     * Maximum number of self-healing retries for this phase.
     * Overrides the global `maxRetries` setting.
     */
    max_retries?: number;
    /**
     * The real MCP-server phase ID string (format: `phase-NNN-<uuid>`).
     * Set by the Engine when a phase is dispatched to a worker.
     * Used by the Webview to construct valid `coogent://` resource URIs.
     */
    mcpPhaseId?: string;
}

/** Global status of the runbook execution. */
export type RunbookStatus = 'idle' | 'running' | 'paused_error' | 'completed';

/** The persistent state file: .task-runbook.json */
export interface Runbook {
    /** Unique identifier for this execution run. */
    readonly project_id: string;
    /** Global execution status. */
    status: RunbookStatus;
    /** Index of the currently executing (or next-to-execute) phase. */
    current_phase: number;
    /** Ordered collection of micro-tasks.
     *  W-11: Not readonly — Engine mutates phase status/fields in-place. Immutability is by convention. */
    phases: Phase[];
    /** Short human-readable summary generated during the Task Planning phase. */
    summary?: string;
    /** Detailed implementation plan markdown generated during the Task Planning phase. */
    implementation_plan?: string;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  2. Finite State Machine — Engine states and events
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * The 9 deterministic states of the execution engine.
 * See ARCHITECTURE.md § State Machine for the transition diagram.
 */
export enum EngineState {
    /** No runbook loaded. Waiting for user action. */
    IDLE = 'IDLE',
    /** Planner agent is generating a runbook from user prompt. */
    PLANNING = 'PLANNING',
    /** AI-generated plan awaiting user review/approval. */
    PLAN_REVIEW = 'PLAN_REVIEW',
    /** Validating .task-runbook.json schema and file existence. */
    PARSING = 'PARSING',
    /** Runbook parsed successfully. Awaiting START command. */
    READY = 'READY',
    /** A worker agent is alive and processing the current phase. */
    EXECUTING_WORKER = 'EXECUTING_WORKER',
    /** Worker exited. Checking success_criteria. */
    EVALUATING = 'EVALUATING',
    /** Phase failed or worker crashed. Halted for user decision. */
    ERROR_PAUSED = 'ERROR_PAUSED',
    /** All phases passed. Terminal state for the run. */
    COMPLETED = 'COMPLETED',
}

/** Events that trigger state transitions. */
export enum EngineEvent {
    PLAN_REQUEST = 'PLAN_REQUEST',
    PLAN_GENERATED = 'PLAN_GENERATED',
    PLAN_APPROVED = 'PLAN_APPROVED',
    PLAN_REJECTED = 'PLAN_REJECTED',
    LOAD_RUNBOOK = 'LOAD_RUNBOOK',
    PARSE_SUCCESS = 'PARSE_SUCCESS',
    PARSE_FAILURE = 'PARSE_FAILURE',
    START = 'START',
    RESUME = 'RESUME',
    WORKER_EXITED = 'WORKER_EXITED',
    PHASE_PASS = 'PHASE_PASS',
    PHASE_FAIL = 'PHASE_FAIL',
    ALL_PHASES_PASS = 'ALL_PHASES_PASS',
    WORKER_TIMEOUT = 'WORKER_TIMEOUT',
    WORKER_CRASH = 'WORKER_CRASH',
    RETRY = 'RETRY',
    SKIP_PHASE = 'SKIP_PHASE',
    ABORT = 'ABORT',
    RESET = 'RESET',
    PAUSE = 'PAUSE',
}

/**
 * The deterministic transition table.
 * Key: current state → Key: event → Value: next state.
 * Missing entries are invalid transitions (silently rejected).
 */
export const STATE_TRANSITIONS: Record<
    EngineState,
    Partial<Record<EngineEvent, EngineState>>
> = {
    [EngineState.IDLE]: {
        [EngineEvent.PLAN_REQUEST]: EngineState.PLANNING,
        [EngineEvent.LOAD_RUNBOOK]: EngineState.PARSING,
        [EngineEvent.RESET]: EngineState.IDLE,
    },
    [EngineState.PLANNING]: {
        [EngineEvent.PLAN_GENERATED]: EngineState.PLAN_REVIEW,
        [EngineEvent.PLAN_REJECTED]: EngineState.PLANNING, // Self-loop for re-plan
        [EngineEvent.ABORT]: EngineState.IDLE,
        [EngineEvent.RESET]: EngineState.IDLE,
    },
    [EngineState.PLAN_REVIEW]: {
        [EngineEvent.PLAN_APPROVED]: EngineState.PARSING,
        [EngineEvent.PLAN_REJECTED]: EngineState.PLANNING,
        [EngineEvent.ABORT]: EngineState.IDLE,
        [EngineEvent.RESET]: EngineState.IDLE,
    },
    [EngineState.PARSING]: {
        [EngineEvent.PARSE_SUCCESS]: EngineState.READY,
        [EngineEvent.PARSE_FAILURE]: EngineState.IDLE,
        [EngineEvent.ABORT]: EngineState.IDLE,
        [EngineEvent.RESET]: EngineState.IDLE,
    },
    [EngineState.READY]: {
        [EngineEvent.START]: EngineState.EXECUTING_WORKER,
        [EngineEvent.RESUME]: EngineState.EXECUTING_WORKER,
        [EngineEvent.ABORT]: EngineState.IDLE,
        [EngineEvent.RESET]: EngineState.IDLE,
    },
    [EngineState.EXECUTING_WORKER]: {
        [EngineEvent.WORKER_EXITED]: EngineState.EVALUATING,
        [EngineEvent.WORKER_TIMEOUT]: EngineState.ERROR_PAUSED,
        [EngineEvent.WORKER_CRASH]: EngineState.ERROR_PAUSED,
        [EngineEvent.ABORT]: EngineState.IDLE,
        [EngineEvent.RESET]: EngineState.IDLE,
    },
    [EngineState.EVALUATING]: {
        [EngineEvent.PHASE_PASS]: EngineState.EXECUTING_WORKER,
        [EngineEvent.ALL_PHASES_PASS]: EngineState.COMPLETED,
        [EngineEvent.PHASE_FAIL]: EngineState.ERROR_PAUSED,
        [EngineEvent.ABORT]: EngineState.IDLE,
        [EngineEvent.RESET]: EngineState.IDLE,
        [EngineEvent.RETRY]: EngineState.EXECUTING_WORKER, // Self-healing retry from evaluating
    },
    [EngineState.ERROR_PAUSED]: {
        [EngineEvent.RETRY]: EngineState.EXECUTING_WORKER,
        [EngineEvent.SKIP_PHASE]: EngineState.READY,
        [EngineEvent.ABORT]: EngineState.IDLE,
        [EngineEvent.RESET]: EngineState.IDLE,
    },
    [EngineState.COMPLETED]: {
        [EngineEvent.RESET]: EngineState.IDLE,
    },
};

// ═══════════════════════════════════════════════════════════════════════════════
//  3. IPC Message Contracts — Webview ↔ Extension Host
// ═══════════════════════════════════════════════════════════════════════════════

/** Token count breakdown per file. */
export interface FileTokenEntry {
    readonly path: string;
    readonly tokens: number;
}

// ── Host → Webview (state projections) ──────────────────────────────────────

export interface StateSnapshotMessage {
    readonly type: 'STATE_SNAPSHOT';
    readonly payload: {
        runbook: Runbook;
        engineState: EngineState;
        /**
         * The real session directory name used as the MCP task key.
         * Populated from `path.basename(sessionDir)` by the Extension Host.
         * The Webview uses this (not `runbook.project_id`) for URI construction.
         */
        masterTaskId?: string;
    };
}

export interface PhaseStatusMessage {
    readonly type: 'PHASE_STATUS';
    readonly payload: {
        phaseId: PhaseId;
        status: PhaseStatus;
        durationMs?: number;
    };
}



export interface TokenBudgetMessage {
    readonly type: 'TOKEN_BUDGET';
    readonly payload: {
        phaseId: PhaseId;
        breakdown: readonly FileTokenEntry[];
        totalTokens: number;
        limit: number;
    };
}

/** Known error codes for typed error handling. */
export type ErrorCode =
    | 'RUNBOOK_NOT_FOUND'
    | 'PARSE_ERROR'
    | 'PHASE_FAILED'
    | 'WORKER_TIMEOUT'
    | 'WORKER_CRASH'
    | 'CYCLE_DETECTED'
    | 'VALIDATION_ERROR'
    | 'CONTEXT_ERROR'
    | 'PLAN_ERROR'
    | 'TOKEN_OVER_BUDGET'
    | 'COMMAND_ERROR'
    | 'GIT_DIRTY'
    | 'UNKNOWN';

export interface ErrorMessage {
    readonly type: 'ERROR';
    readonly payload: {
        code: ErrorCode;
        message: string;
        phaseId?: PhaseId;
    };
}

export interface LogEntryMessage {
    readonly type: 'LOG_ENTRY';
    readonly payload: {
        timestamp: UnixTimestampMs;
        level: 'info' | 'warn' | 'error';
        message: string;
    };
}

/** Planning draft message — planner agent produced a runbook draft. */
export interface PlanDraftMessage {
    readonly type: 'PLAN_DRAFT';
    readonly payload: {
        draft: Runbook;
        fileTree: readonly string[];
    };
}

/** Planning status message — spinner updates during planning. */
export interface PlanStatusMessage {
    readonly type: 'PLAN_STATUS';
    readonly payload: {
        status: 'generating' | 'parsing' | 'ready' | 'error' | 'timeout';
        message?: string;
    };
}

/** Session list message — recent sessions for the history drawer. */
export interface SessionListMessage {
    readonly type: 'SESSION_LIST';
    readonly payload: {
        sessions: readonly SessionSummary[];
    };
}

/** Session search results message — filtered sessions from a search query. */
export interface SessionSearchResultsMessage {
    readonly type: 'SESSION_SEARCH_RESULTS';
    readonly payload: {
        query: string;
        sessions: readonly SessionSummary[];
    };
}

/** Conversation mode sync message — tells the Webview which mode is active. */
export interface ConversationModeMessage {
    readonly type: 'CONVERSATION_MODE';
    readonly payload: {
        mode: ConversationMode;
        smartSwitchTokenThreshold: number;
    };
}

/** Consolidation report message — final report after all phases pass. */
export interface ConsolidationReportMessage {
    readonly type: 'CONSOLIDATION_REPORT';
    readonly payload: {
        /** Markdown-formatted consolidation report. */
        report: string;
    };
}

/** Per-phase worker output — routes output to specific phase detail views. */
export interface PhaseOutputMessage {
    readonly type: 'PHASE_OUTPUT';
    readonly payload: {
        phaseId: PhaseId;
        stream: 'stdout' | 'stderr';
        chunk: string;
    };
}

/** Planning summary message — delivers planning phase output for the review gate. */
export interface PlanSummaryMessage {
    readonly type: 'PLAN_SUMMARY';
    readonly payload: {
        summary: string;
    };
}

/** Implementation plan message — markdown content of implementation_plan.md. */
export interface ImplementationPlanMessage {
    readonly type: 'IMPLEMENTATION_PLAN';
    readonly payload: {
        /** Markdown-formatted implementation plan. */
        plan: string;
    };
}

/** MCP resource data response — Extension Host → Webview. */
export interface MCPResourceDataMessage {
    readonly type: 'MCP_RESOURCE_DATA';
    readonly payload: {
        /** Correlation ID matching the original fetch request. */
        requestId: string;
        /** The resolved resource content (string for Markdown/plain text, object for JSON). */
        data: string | object;
        /** Error message if the resource could not be resolved. */
        error?: string;
    };
}


/** Suggestion items for @ mention and / workflow popups. */
export interface SuggestionDataMessage {
    readonly type: 'SUGGESTION_DATA';
    readonly payload: {
        mentions: readonly { label: string; description: string; insert: string }[];
        workflows: readonly { label: string; description: string; insert: string }[];
    };
}

/** File/image attachment selection result from the Extension Host. */
export interface AttachmentSelectedMessage {
    readonly type: 'ATTACHMENT_SELECTED';
    readonly payload: {
        paths: readonly string[];
    };
}

/**
 * Discriminated union of all messages the Extension Host sends to the Webview.
 * Use `HostToWebviewMessageType` for the `type` string literal union.
 */
export type HostToWebviewMessage =
    | StateSnapshotMessage
    | PhaseStatusMessage
    | TokenBudgetMessage
    | ErrorMessage
    | LogEntryMessage
    | PlanDraftMessage
    | PlanStatusMessage
    | SessionListMessage
    | SessionSearchResultsMessage
    | ConversationModeMessage
    | ConsolidationReportMessage
    | PhaseOutputMessage
    | PlanSummaryMessage
    | ImplementationPlanMessage
    | MCPResourceDataMessage
    | SuggestionDataMessage
    | AttachmentSelectedMessage;

// ── Webview → Host (user commands) ──────────────────────────────────────────

/**
 * Dual-purpose start/resume command.
 * When the engine is in READY state, this starts execution.
 * When the engine is paused (cooperative pause via flag), this resumes.
 */
export interface CmdStartMessage {
    readonly type: 'CMD_START';
}



export interface CmdAbortMessage {
    readonly type: 'CMD_ABORT';
}

export interface CmdRetryMessage {
    readonly type: 'CMD_RETRY';
    readonly payload: { phaseId: PhaseId };
}

export interface CmdSkipPhaseMessage {
    readonly type: 'CMD_SKIP_PHASE';
    readonly payload: { phaseId: PhaseId };
}

export interface CmdPausePhaseMessage {
    readonly type: 'CMD_PAUSE_PHASE';
    readonly payload: { phaseId: PhaseId };
}

export interface CmdStopPhaseMessage {
    readonly type: 'CMD_STOP_PHASE';
    readonly payload: { phaseId: PhaseId };
}

export interface CmdRestartPhaseMessage {
    readonly type: 'CMD_RESTART_PHASE';
    readonly payload: { phaseId: PhaseId };
}

export interface CmdEditPhaseMessage {
    readonly type: 'CMD_EDIT_PHASE';
    readonly payload: {
        phaseId: PhaseId;
        patch: Partial<Pick<Phase, 'prompt' | 'context_files' | 'success_criteria'>>;
    };
}

export interface CmdLoadRunbookMessage {
    readonly type: 'CMD_LOAD_RUNBOOK';
    readonly payload?: { filePath: string };
}

export interface CmdRequestStateMessage {
    readonly type: 'CMD_REQUEST_STATE';
}

/** User submits a prompt for the Planner Agent to generate a runbook. */
export interface CmdPlanRequestMessage {
    readonly type: 'CMD_PLAN_REQUEST';
    readonly payload: {
        prompt: string;
        feedback?: string;
    };
}

/** User approves the AI-generated plan. */
export interface CmdPlanApproveMessage {
    readonly type: 'CMD_PLAN_APPROVE';
}

/** User rejects the plan and provides feedback for re-generation. */
export interface CmdPlanRejectMessage {
    readonly type: 'CMD_PLAN_REJECT';
    readonly payload: {
        feedback: string;
    };
}

/** User edits the draft runbook directly in the review panel. */
export interface CmdPlanEditDraftMessage {
    readonly type: 'CMD_PLAN_EDIT_DRAFT';
    readonly payload: {
        draft: Runbook;
    };
}

/** User requests re-parsing of cached timeout output (no full re-generation). */
export interface CmdPlanRetryParseMessage {
    readonly type: 'CMD_PLAN_RETRY_PARSE';
}

/** User requests a full reset (start new chat) from COMPLETED state. */
export interface CmdResetMessage {
    readonly type: 'CMD_RESET';
}

/** User requests the list of recent/past sessions. */
export interface CmdListSessionsMessage {
    readonly type: 'CMD_LIST_SESSIONS';
}

/** User searches past sessions by query string. */
export interface CmdSearchSessionsMessage {
    readonly type: 'CMD_SEARCH_SESSIONS';
    readonly payload: {
        query: string;
    };
}

/** User loads a specific past session by ID. */
export interface CmdLoadSessionMessage {
    readonly type: 'CMD_LOAD_SESSION';
    readonly payload: {
        sessionId: string;
    };
}

/** User sets the conversation mode via the toggle. */
export interface CmdSetConversationModeMessage {
    readonly type: 'CMD_SET_CONVERSATION_MODE';
    readonly payload: {
        mode: ConversationMode;
    };
}

/** User requests the consolidation report for the current session. */
export interface CmdRequestReportMessage {
    readonly type: 'CMD_REQUEST_REPORT';
}

/** User requests the implementation plan for the current session. */
export interface CmdRequestPlanMessage {
    readonly type: 'CMD_REQUEST_PLAN';
}

/** User deletes a session from history. */
export interface CmdDeleteSessionMessage {
    readonly type: 'CMD_DELETE_SESSION';
    readonly payload: {
        sessionId: string;
    };
}

/** User requests to review a diff for a specific phase. */
export interface CmdReviewDiffMessage {
    readonly type: 'CMD_REVIEW_DIFF';
    readonly payload: {
        phaseId: PhaseId;
    };
}

/** User requests to resume all pending phases with satisfied dependencies. */
export interface CmdResumePendingMessage {
    readonly type: 'CMD_RESUME_PENDING';
}

/** Webview requests a specific MCP resource by URI. */
export interface MCPFetchResourceMessage {
    readonly type: 'MCP_FETCH_RESOURCE';
    readonly payload: {
        /** The `coogent://` URI to resolve. */
        uri: string;
        /** Unique correlation ID for async response matching. */
        requestId: string;
    };
}

/** User requests to attach a file from the workspace. */
export interface CmdUploadFileMessage {
    readonly type: 'CMD_UPLOAD_FILE';
}

/** User requests to attach an image from the workspace. */
export interface CmdUploadImageMessage {
    readonly type: 'CMD_UPLOAD_IMAGE';
}

/**
 * Discriminated union of all messages the Webview sends to the Extension Host.
 * Use `WebviewToHostMessageType` for the `type` string literal union.
 */
export type WebviewToHostMessage =
    | CmdStartMessage
    | CmdAbortMessage
    | CmdRetryMessage
    | CmdSkipPhaseMessage
    | CmdPausePhaseMessage
    | CmdStopPhaseMessage
    | CmdRestartPhaseMessage
    | CmdEditPhaseMessage
    | CmdLoadRunbookMessage
    | CmdResetMessage
    | CmdRequestStateMessage
    | CmdPlanRequestMessage
    | CmdPlanApproveMessage
    | CmdPlanRejectMessage
    | CmdPlanEditDraftMessage
    | CmdPlanRetryParseMessage
    | CmdSetConversationModeMessage
    | CmdRequestReportMessage
    | CmdRequestPlanMessage
    | CmdReviewDiffMessage
    | CmdResumePendingMessage
    | MCPFetchResourceMessage
    | CmdUploadFileMessage
    | CmdUploadImageMessage
    | CmdListSessionsMessage
    | CmdSearchSessionsMessage
    | CmdLoadSessionMessage
    | CmdDeleteSessionMessage;

/** Helper: union of all Host → Webview message type string literals (#95). */
export type HostToWebviewMessageType = HostToWebviewMessage['type'];

/** Helper: union of all Webview → Host message type string literals (#95). */
export type WebviewToHostMessageType = WebviewToHostMessage['type'];

// ═══════════════════════════════════════════════════════════════════════════════
//  4. ADK Integration Contracts
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * The payload sent to the ADK when spawning an ephemeral worker agent.
 * Enforces zero-context mode and explicit file injection.
 */
export interface ADKInjectionPayload {
    /**
     * MUST be `true`. Workers are always ephemeral — no conversation history,
     * no prior file access, no accumulated state.
     */
    readonly ephemeral: true;
    /** The micro-task prompt to inject into the worker. */
    readonly prompt: string;
    /**
     * Pre-assembled, delimited file content payload.
     * Format: `<<<FILE: path>>>..content..<<<END FILE>>>` per file.
     */
    readonly contextPayload: string;
    /** Workspace root for the worker agent. */
    readonly workingDirectory: string;
    /** Maximum execution time before force-termination (ms). */
    readonly timeoutMs: number;
}

/**
 * Handle returned by the ADK after spawning a worker.
 * Used for monitoring and termination.
 */
export interface ADKWorkerHandle {
    /** Unique session identifier from the ADK. */
    readonly sessionId: string;
    /** OS process ID of the worker (for orphan cleanup). */
    readonly pid: number;
    /** Register a callback for stdout/stderr output chunks. Returns an unsubscribe function. */
    onOutput(callback: (stream: 'stdout' | 'stderr', chunk: string) => void): () => void;
    /** Register a callback for process exit. Returns an unsubscribe function. */
    onExit(callback: (exitCode: number) => void): () => void;
    /** Force-terminate the worker process. */
    terminate(): Promise<void>;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  5. Context Scoper Result Types
// ═══════════════════════════════════════════════════════════════════════════════

/** Successful context assembly result. */
export interface ContextResultOk {
    readonly ok: true;
    readonly payload: string;
    readonly totalTokens: number;
    readonly limit: number;
    readonly breakdown: readonly FileTokenEntry[];
}

/** Failed context assembly — token budget exceeded. */
export interface ContextResultOverBudget {
    readonly ok: false;
    readonly totalTokens: number;
    readonly limit: number;
    readonly breakdown: readonly FileTokenEntry[];
}

/** Result of the Context Scoper's assembly operation. */
export type ContextResult = ContextResultOk | ContextResultOverBudget;

// ═══════════════════════════════════════════════════════════════════════════════
//  6. WAL (Write-Ahead Log) Entry
// ═══════════════════════════════════════════════════════════════════════════════

/** A WAL entry written before mutating the runbook file. */
export interface WALEntry {
    readonly timestamp: UnixTimestampMs;
    readonly engineState: EngineState;
    readonly currentPhase: number;
    readonly snapshot: Runbook;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  7. Pillar 2 — Intelligent Context Management Types
// ═══════════════════════════════════════════════════════════════════════════════

/** Pluggable interface for resolving context file paths. */
export interface FileResolver {
    /**
     * Resolve the full set of files to inject for a phase.
     * V1: Returns `phase.context_files` verbatim (explicit).
     * V2: Walks the AST to discover transitive imports.
     */
    resolve(phase: Phase, workspaceRoot: string): Promise<string[]>;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  8. Pillar 3 — Autonomous Resilience Types
// ═══════════════════════════════════════════════════════════════════════════════

/** Evaluator type discriminant. */
export type EvaluatorType = 'exit_code' | 'regex' | 'toolchain' | 'test_suite';

/**
 * Pluggable interface for evaluating phase success.
 * Implementations can verify exit codes, regex on stdout, compiler output, etc.
 */
export interface SuccessEvaluator {
    /** Unique type identifier (matches `phase.evaluator`). */
    readonly type: EvaluatorType;
    /**
     * Evaluate whether a phase succeeded.
     * @returns `true` if the phase should be marked as passed.
     */
    evaluate(criteria: string, exitCode: number, stdout: string, stderr: string): Promise<boolean>;
}

/** Result of a self-healing attempt. */
export interface HealingAttempt {
    readonly attemptNumber: number;
    readonly phaseId: PhaseId;
    readonly exitCode: number;
    readonly stderr: string;
    readonly timestamp: UnixTimestampMs;
}

/** Git operation result. */
export interface GitOperationResult {
    readonly success: boolean;
    readonly commitHash?: string;
    readonly message: string;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  9. Git Sandbox Manager Types
// ═══════════════════════════════════════════════════════════════════════════════

/** Result of a Git sandbox branch operation (create / cleanup). */
export interface GitSandboxResult {
    success: boolean;
    branchName?: string;
    previousBranch?: string;
    message: string;
}

/** Result of the pre-flight check before entering the sandbox. */
export interface PreFlightCheckResult {
    clean: boolean;
    currentBranch: string;
    message: string;
}

/** Options for creating a Git sandbox branch. */
export interface SandboxOptions {
    taskSlug: string;
    /** Branch name prefix (default concept: 'coogent/'). */
    branchPrefix?: string;
}
