// ─────────────────────────────────────────────────────────────────────────────
// src/types/phase.ts — Runbook, Phase, branded types, and context contracts
// ─────────────────────────────────────────────────────────────────────────────

import type { EvaluatorType } from './evaluators.js';

// ═══════════════════════════════════════════════════════════════════════════════
//  0. Conversation Mode — Controls how subtask conversations are managed
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Controls how the AI chat conversation is managed across subtask phases.
 * - `isolated`: Each subtask opens a new conversation (zero-context, default).
 * - `continuous`: All subtasks share the same conversation (context carries over).
 * - `smart`: Automatically starts a new conversation when estimated token usage
 *   crosses a configurable threshold.
 */
export type ConversationMode = 'isolated' | 'continuous' | 'smart';

/** Configuration for conversation management across subtasks. */
export interface ConversationSettings {
    /** Active conversation mode. */
    mode: ConversationMode;
    /** Token threshold for smart-switch mode (default: 80_000). */
    smartSwitchTokenThreshold: number;
}

/** Default conversation settings. */
export const DEFAULT_CONVERSATION_SETTINGS: ConversationSettings = {
    mode: 'isolated',
    smartSwitchTokenThreshold: 80_000,
};



// ═══════════════════════════════════════════════════════════════════════════════
//  Branded Types — nominal type safety for opaque IDs and timestamps
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Nominal branded type for phase identifiers.
 * Prevents accidental mix-ups between phase IDs and other numbers.
 */
export type PhaseId = number & { readonly __brand: 'PhaseId' };

/**
 * Unix timestamp in milliseconds (Date.now()-style).
 * Branded to distinguish from plain numbers.
 */
export type UnixTimestampMs = number & { readonly __brand: 'UnixTimestampMs' };

/** Cast a plain number to a branded PhaseId. */
export function asPhaseId(n: number): PhaseId {
    return n as PhaseId;
}

/** Cast Date.now() or similar to a branded UnixTimestampMs. */
export function asTimestamp(ms: number = Date.now()): UnixTimestampMs {
    return ms as UnixTimestampMs;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  1. Runbook Data Model — .task-runbook.json schema
//
//  Naming convention (#92):
//    - snake_case for JSON-persisted fields (project_id, context_files, depends_on)
//    - camelCase for TypeScript-only runtime fields (smartSwitchTokenThreshold)
// ═══════════════════════════════════════════════════════════════════════════════

/** Status of an individual phase within the runbook. */
export type PhaseStatus = 'pending' | 'running' | 'completed' | 'failed';

/** A single micro-task within the runbook execution plan. */
export interface Phase {
    /** Sequential identifier (or DAG node ID in V2). */
    readonly id: PhaseId;
    /** Current execution status. */
    status: PhaseStatus;
    /** The explicit instruction to inject into the ephemeral worker agent. */
    prompt: string;
    /** Exact file paths (relative to workspace root) to read and inject.
     *  W-11: Not readonly — Engine mutates in-place. Immutability is by convention. */
    context_files: string[];
    /**
     * The condition required to mark this phase as successful.
     * V1: `"exit_code:0"` — checks process exit code.
     * V2: Regex match, compiler output, test suite result.
     */
    success_criteria: string;

    // ── Pillar 2+3 Extensions (optional, backward-compatible) ────────────

    /**
     * Phase IDs that must complete before this phase can begin.
     * Enables DAG-based parallel execution.
     * When absent, sequential ordering via `current_phase` is used.
     */
    depends_on?: readonly PhaseId[];
    /**
     * Brief context summary explaining what this phase does and why.
     * Generated by the Planner Agent to help users understand the phase at a glance.
     */
    context_summary?: string;
    /**
     * Which evaluator to use for `success_criteria`.
     * V1 default: `"exit_code"`.
     * V2+: `"regex"`, `"toolchain"`, `"test_suite"`.
     */
    evaluator?: EvaluatorType;
    /**
     * List of evaluators to run in composite mode.
     * When present, takes precedence over `evaluator` — all evaluators
     * run in sequence and the phase fails if ANY evaluator fails.
     */
    evaluators?: EvaluatorType[];
    /**
     * Maximum number of self-healing retries for this phase.
     * Overrides the global `maxRetries` setting.
     */
    max_retries?: number;
    /**
     * Capability tags requested by the Planner for this phase.
     * Used by the AgentRegistry to select the best-matching AgentProfile.
     * When absent, the default generalist worker is used.
     */
    required_capabilities?: string[];
    /**
     * The real MCP-server phase ID string (format: `phase-NNN-<uuid>`).
     * Set by the Engine when a phase is dispatched to a worker.
     * Used by the Webview to construct valid `coogent://` resource URIs.
     */
    mcpPhaseId?: string;
    /**
     * When true, all context files for this phase receive `full` mode.
     * Useful for review or architecture phases that need complete file understanding.
     */
    requiresFullFileContext?: boolean;
}

/** Global status of the runbook execution. */
export type RunbookStatus = 'idle' | 'running' | 'paused_error' | 'completed';

/** The persistent state file: .task-runbook.json */
export interface Runbook {
    /** Unique identifier for this execution run. */
    readonly project_id: string;
    /** Global execution status. */
    status: RunbookStatus;
    /** Index of the currently executing (or next-to-execute) phase. */
    current_phase: number;
    /** Ordered collection of micro-tasks.
     *  W-11: Not readonly — Engine mutates phase status/fields in-place. Immutability is by convention. */
    phases: Phase[];
    /** Short human-readable summary generated during the Task Planning phase. */
    summary?: string;
    /** Detailed implementation plan markdown generated during the Task Planning phase. */
    implementation_plan?: string;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  Context Scoper Result Types
// ═══════════════════════════════════════════════════════════════════════════════

/** Token count breakdown per file. */
export interface FileTokenEntry {
    readonly path: string;
    readonly tokens: number;
}

/** Successful context assembly result. */
export interface ContextResultOk {
    readonly ok: true;
    readonly payload: string;
    readonly totalTokens: number;
    readonly limit: number;
    readonly breakdown: readonly FileTokenEntry[];
}

/** Failed context assembly — token budget exceeded. */
export interface ContextResultOverBudget {
    readonly ok: false;
    readonly totalTokens: number;
    readonly limit: number;
    readonly breakdown: readonly FileTokenEntry[];
}

/** Result of the Context Scoper's assembly operation. */
export type ContextResult = ContextResultOk | ContextResultOverBudget;

// ═══════════════════════════════════════════════════════════════════════════════
//  WAL (Write-Ahead Log) Entry
// ═══════════════════════════════════════════════════════════════════════════════

/** A WAL entry written before mutating the runbook file. */
export interface WALEntry {
    readonly timestamp: UnixTimestampMs;
    readonly engineState: import('./engine.js').EngineState;
    readonly currentPhase: number;
    readonly snapshot: Runbook;
}

// ═══════════════════════════════════════════════════════════════════════════════
//  Pluggable Context Resolution
// ═══════════════════════════════════════════════════════════════════════════════

/** Pluggable interface for resolving context file paths. */
export interface FileResolver {
    /**
     * Resolve the full set of files to inject for a phase.
     * V1: Returns `phase.context_files` verbatim (explicit).
     * V2: Walks the AST to discover transitive imports.
     */
    resolve(phase: Phase, workspaceRoot: string): Promise<string[]>;

    /**
     * Resolve files across multiple workspace roots.
     * Optional — when absent, callers should fall back to `resolve()` with `roots[0]`.
     * Implementations should try each root and handle ambiguous paths gracefully.
     */
    resolveMultiRoot?(phase: Phase, workspaceRoots: string[]): Promise<string[]>;
}
